"""add correlation_id to outbox_events

Revision ID: 4fa2b1412a32
Revises: 002
Create Date: 2026-08-12 20:44:03.106437
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4fa2b1412a32'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'correlation_id')
    # ### end Alembic commands ###
